apiVersion: v1
entries:
  cc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-25T14:39:17.9850625Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: fa399641794b2e1372492ed586dff8d2d388efcc933edf568b6d5a46273e1e77
    home: cc.zaakonline.nl
    icon: cc.zaakonline.nl
    name: cc
    urls:
    - cc-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-25T14:39:17.9568711Z"
