apiVersion: v1
entries:
  cc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-28T11:01:08.9647797Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 7c0963276503b5c761b0370690c083b4e68f026825ac62867199bbe5725088f0
    home: cc.zaakonline.nl
    icon: cc.zaakonline.nl
    name: cc
    urls:
    - cc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2020-12-28T11:01:08.974292Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
generated: "2020-12-28T11:01:08.9576828Z"
