apiVersion: v1
entries:
  contactcatalogus:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2021-12-16T09:17:36.0507066Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
    description: Het Contacten Component bevat lijsten van contactpersonen, hiermee
      heeft het vanuit bron perspectief doorgaans een aanvullende of vervangende taak
      ten opzichte van het BRP. Met andere woorden in het Contacten Component vinden
      we personen die we niet uit het BRP halen. Dat kan zijn, omdat deze personen
      niet in het BRP staan, we nog niet weten wat het BSN van een persoon is of omdat
      we simpelweg geen rechten of toegang hebben tot het BRP vanuit het proces waar
      we mee bezig zijn. Daarnaast fungeert het Contacten Component als een Common
      Ground variant van de contactpersonenlijst, zoals we die kennen vanuit een e-mail
      applicatie of telefoon. Het is dus ook mogelijk om personen op te nemen in een
      contactenlijst. Hiermee worden contact en functionaliteiten voor gebruikers
      (in application form) gerealiseerd. Als laatste biedt het Contacten Component
      de mogelijkheid om gegevens van organisaties op te slaan. Het component ondersteunt
      bewust alleen de persoonsgegevens, maar kan in samenwerking met het CMR en ORC
      een Customer Relation Management systeem vormen, waarbij het ORC de mogelijkheid
      biedt om bijvoorbeeld leads in kaart te brengen.
    digest: be88788cc99ddf2d3003b1e88b7d90906075cf33776196b175f8780a50484077
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: contactcatalogus
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - contactcatalogus-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-12-16T09:17:36.0322347Z"
    description: Het Contacten Component bevat lijsten van contactpersonen, hiermee
      heeft het vanuit bron perspectief doorgaans een aanvullende of vervangende taak
      ten opzichte van het BRP. Met andere woorden in het Contacten Component vinden
      we personen die we niet uit het BRP halen. Dat kan zijn, omdat deze personen
      niet in het BRP staan, we nog niet weten wat het BSN van een persoon is of omdat
      we simpelweg geen rechten of toegang hebben tot het BRP vanuit het proces waar
      we mee bezig zijn. Daarnaast fungeert het Contacten Component als een Common
      Ground variant van de contactpersonenlijst, zoals we die kennen vanuit een e-mail
      applicatie of telefoon. Het is dus ook mogelijk om personen op te nemen in een
      contactenlijst. Hiermee worden contact en functionaliteiten voor gebruikers
      (in application form) gerealiseerd. Als laatste biedt het Contacten Component
      de mogelijkheid om gegevens van organisaties op te slaan. Het component ondersteunt
      bewust alleen de persoonsgegevens, maar kan in samenwerking met het CMR en ORC
      een Customer Relation Management systeem vormen, waarbij het ORC de mogelijkheid
      biedt om bijvoorbeeld leads in kaart te brengen.
    digest: 22eff6cf52ecbe5e39e09a0576ec8e10114c50f123a9eab64b001184c6e0ece5
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: contactcatalogus
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - contactcatalogus-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-12-16T09:17:36.0634474Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.0.11
    created: "2021-12-16T09:17:36.0771802Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: 2d70861d16fc410ed6d6c818b97f7b0d519031147e5c7b42c5691d4c38742c44
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-12.7.7.tgz
    version: 12.7.7
generated: "2021-12-16T09:17:36.0010741Z"
