apiVersion: v1
entries:
  contactcatalogus:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-06-18T10:02:10.9793275Z"
    description: Het Contacten Component bevat lijsten van contactpersonen, hiermee
      heeft het vanuit bron perspectief doorgaans een aanvullende of vervangende taak
      ten opzichte van het BRP. Met andere woorden in het Contacten Component vinden
      we personen die we niet uit het BRP halen. Dat kan zijn, omdat deze personen
      niet in het BRP staan, we nog niet weten wat het BSN van een persoon is of omdat
      we simpelweg geen rechten of toegang hebben tot het BRP vanuit het proces waar
      we mee bezig zijn. Daarnaast fungeert het Contacten Component als een Common
      Ground variant van de contactpersonenlijst, zoals we die kennen vanuit een e-mail
      applicatie of telefoon. Het is dus ook mogelijk om personen op te nemen in een
      contactenlijst. Hiermee worden contact en functionaliteiten voor gebruikers
      (in application form) gerealiseerd. Als laatste biedt het Contacten Component
      de mogelijkheid om gegevens van organisaties op te slaan. Het component ondersteunt
      bewust alleen de persoonsgegevens, maar kan in samenwerking met het CMR en ORC
      een Customer Relation Management systeem vormen, waarbij het ORC de mogelijkheid
      biedt om bijvoorbeeld leads in kaart te brengen.
    digest: ad668e4353c14e90197d11beff9c769bc440db54c30ccdb2e0c42ba2ad02bbf5
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: contactcatalogus
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - contactcatalogus-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-06-18T10:02:10.9847177Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2021-06-18T10:02:10.9658183Z"
