name: Artifact Register

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master


jobs:
    register:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Check if we need to take action
              id: process
              run: |
                  export ARTIFACTHUB_ID=$(grep ARTIFACTHUB_ID= .env | cut -d '=' -f2)
                  if [ "${{ secrets.ARTIFACT_KEY }}" != "" ] && [ "$ARTIFACTHUB_ID" != "false" ] || [ "ARTIFACTHUB_ID" == "" ]; then
                    echo "##[set-output name=success;]true"
                  else
                    echo "##[set-output name=success;]false"
                  fi
            - name: defining variables
              id: request
              if: steps.process.outputs.success == 'true'
              run: |
                  export HEADER="{'X-API-KEY': '"${{secrets.ARTIFACT_KEY}}"'}"
                  echo "HEADER=$HEADER" >> $GITHUB_ENV
                  echo "##[set-output name=header]$HEADER"
                  export USER=$(grep ARTIFACTHUB_USER= .env | cut -d '=' -f2)
                  if [ $USER != "" ]; then
                    export URL="https://artifacthub.io/api/v1/repositories/org/$USER"
                  else
                    export URL='https://artifacthub.io/api/v1/repositories/user'
                  fi
                  echo "URL=$URL" >> $GITHUB_ENV
                  echo "##[set-output name=url]$URL"
                  export HELM=$(grep HELM_REPOSITORY= .env | cut -d '=' -f2)
                  export NAME=$(grep APP_NAME_TECHNICAL= .env | cut -d '=' -f2)
                  export DATA='{"url": "'$HELM'", "name": "'$NAME'"}'
                  echo "DATA=$DATA" >> $GITHUB_ENV
                  echo "##[set-output name=data]$DATA"
            - name: Register To Artifact Hub
              if: steps.process.outputs.success == 'true'
              uses: CamiloGarciaLaRotta/watermelon-http-client@v1
              with:
                headers: '{"X-API-KEY": "test"}'
                url: steps.request.url
                method: post
                data: steps.request.data
            - name: Print the response status
              run: echo ${{ steps.request.outputs.status }}
            - name: Print the response payload
              run: echo ${{ steps.request.outputs.response }}
